import React from 'react';
import { ValuationData } from '../types';
import { Scale, AlertCircle } from 'lucide-react';

interface ValuationCardProps {
  data: ValuationData;
  currentPrice: number;
}

const ValuationCard: React.FC<ValuationCardProps> = ({ data, currentPrice }) => {
  const diff = ((data.estimatedFairValue - currentPrice) / currentPrice) * 100;
  const isUndervalued = diff > 0;

  return (
    <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
      
      {/* Main Valuation Status */}
      <div className="bg-slate-900 border border-slate-800 rounded-xl p-6 relative overflow-hidden">
        <div className={`absolute top-0 right-0 w-32 h-32 rounded-full blur-3xl opacity-10 ${isUndervalued ? 'bg-green-500' : 'bg-red-500'}`}></div>
        
        <div className="flex items-center gap-2 mb-6">
          <Scale className="text-blue-500" size={24} />
          <h3 className="text-lg font-semibold text-white">Fair Value Model</h3>
        </div>

        <div className="flex flex-col gap-8">
          <div>
            <div className="text-sm text-slate-500 mb-1">Current Price</div>
            <div className="text-3xl font-mono font-bold text-white">${currentPrice.toFixed(2)}</div>
          </div>
          
          <div>
            <div className="text-sm text-slate-500 mb-1">Estimated Fair Value</div>
            <div className="flex items-baseline gap-3">
              <div className="text-3xl font-mono font-bold text-blue-400">${data.estimatedFairValue.toFixed(2)}</div>
              <span className={`px-2 py-1 rounded text-xs font-bold ${isUndervalued ? 'bg-green-500/10 text-green-500' : 'bg-red-500/10 text-red-500'}`}>
                {isUndervalued ? 'UNDERVALUED' : 'OVERVALUED'} by {Math.abs(diff).toFixed(1)}%
              </span>
            </div>
          </div>
          
          <div className="pt-4 border-t border-slate-800">
             <div className="flex justify-between items-center mb-2">
                <span className="text-slate-400 text-sm">Recommendation</span>
                <span className={`font-bold ${
                  data.recommendation === 'BUY' ? 'text-green-400' : 
                  data.recommendation === 'SELL' ? 'text-red-400' : 'text-yellow-400'
                }`}>
                  {data.recommendation}
                </span>
             </div>
             <p className="text-sm text-slate-500 leading-relaxed">
               {data.reasoning}
             </p>
          </div>
        </div>
      </div>

      {/* Assumptions & Multiples */}
      <div className="space-y-6">
        <div className="bg-slate-900 border border-slate-800 rounded-xl p-6">
          <h4 className="text-sm font-semibold text-slate-300 mb-4 uppercase tracking-wide">Model Inputs</h4>
          <div className="space-y-4">
            <div className="flex justify-between items-center p-3 bg-slate-950 rounded-lg border border-slate-800">
              <span className="text-slate-400 text-sm">Implied P/E Ratio</span>
              <span className="font-mono text-white">{data.peRatio?.toFixed(2)}x</span>
            </div>
            <div className="flex justify-between items-center p-3 bg-slate-950 rounded-lg border border-slate-800">
              <span className="text-slate-400 text-sm">Industry Avg P/E</span>
              <span className="font-mono text-slate-400">{data.industryAveragePe?.toFixed(2)}x</span>
            </div>
          </div>
        </div>

        <div className="bg-blue-900/10 border border-blue-900/30 rounded-xl p-4 flex gap-3">
          <AlertCircle className="text-blue-500 shrink-0" size={20} />
          <p className="text-xs text-blue-300 leading-relaxed">
            This valuation is generated by Gemini 3 Pro using a comparable multiples approach. 
            It is for informational purposes only and does not constitute financial advice.
          </p>
        </div>
      </div>

    </div>
  );
};

export default ValuationCard;
